command:
  - "uvicorn"
  - "server.app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"

env:
  - name: ENV
    value: "production"
  - name: PROJECTS_BASE_DIR
    value: "./projects"
  - name: ENABLED_SKILLS
    value: "databricks-python-sdk,spark-declarative-pipelines,synthetic-data-generation"

  # Database configuration (choose one approach):
  #
  # Option 1: Dynamic OAuth tokens (recommended for production)
  # Uses Databricks SDK to automatically refresh tokens every 50 minutes
  # - name: LAKEBASE_INSTANCE_NAME
  #   value: "my-lakebase-instance"
  # - name: LAKEBASE_DATABASE_NAME
  #   value: "my_database"
  #
  # Option 2: Static URL with password (for local development)
  # - name: LAKEBASE_PG_URL
  #   valueFrom:
  #     secretKeyRef:
  #       name: lakebase-pg-url
  #       key: url
  #
  # Optional database pool settings:
  # - name: DB_POOL_SIZE
  #   value: "5"
  # - name: DB_MAX_OVERFLOW
  #   value: "10"
  # - name: DB_POOL_TIMEOUT
  #   value: "10"
  # - name: DB_POOL_RECYCLE_INTERVAL
  #   value: "3600"
